version: "3.5"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .:/myapp
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - 5432:5432
    restart: always

volumes:
  postgres_data:
